package com.detex;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.BackingStoreException;
import java.util.prefs.Preferences;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import org.netbeans.lib.awtextra.AbsoluteLayout;

/**
 *
 * @author Daniel
 */
public class WindowFrame extends javax.swing.JFrame {

    private static final long serialVersionUID = 5526085122118509175L;
    //private static final Preferences p = Preferences.systemNodeForPackage(WindowFrame.class);
    public final String[] list = {"EAX2500", "EAX2503", "EAX2504", "EAX2510",
        "EAX2513", "EAX2514", "EAX2520", "EAX2523", "EAX2524", "EAX2545"};

    /**
     * Creates new form WindowFrame
     */
    public WindowFrame() {
//        Preferences p = Preferences.userNodeForPackage(MainInterface.class);
        initComponents();
        for (String s : list) {
            JMenuItem mi = new JMenuItem(s);
            mi.setActionCommand(s);
            mi.addActionListener(al);
            mi.addActionListener((ActionEvent e) -> {
//                textArea.append(e.getActionCommand() + "\n");
                deviceLabel.setText("Device: " + e.getActionCommand());
            });
            mi.setFont(mnAddUser.getFont());
            this.deviceMenu.add(mi);
        }

        /* try {
            boolean found = false;
            for (String s : p.keys()) {
                if (s.equals("WIDTH")) {
                    setSize(p.getInt("WIDTH", this.getWidth()), p.getInt("HEIGHT", getHeight()));
                }
            }
        } catch (BackingStoreException ex) {
            Logger.getLogger(WindowFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.removeWindowListener(getWindowListeners()[0]);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // super.windowClosing(e); //To change body of generated methods, choose Tools | Templates.
                p.putInt("WIDTH", getWidth());
                p.putInt("HEIGHT", getHeight());
                try {
                    p.flush();
                    p.sync();
                } catch (BackingStoreException ex) {
                    Logger.getLogger(WindowFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        passwordDialog = new JDialog();
        jPasswordField1 = new JPasswordField();
        jLabel2 = new JLabel();
        okPasswordBtn = new JButton();
        cancelPassBtn = new JButton();
        jPanel1 = new JPanel();
        pgmBtn = new JButton();
        testBtn = new JButton();
        deviceLabel = new JLabel();
        jScrollPane1 = new JScrollPane();
        textArea = new JTextArea();
        jPanel2 = new JPanel();
        exitBtn = new JButton();
        jLabel3 = new JLabel();
        loginBtn = new JButton();
        userBox = new JComboBox<>();
        jMenuBar1 = new JMenuBar();
        jMenu1 = new JMenu();
        mnQuit = new JMenuItem();
        deviceMenu = new JMenu();
        jMenu3 = new JMenu();
        mnChangePass = new JMenuItem();
        mnChangeColor = new JMenuItem();
        mnTimer = new JMenuItem();
        adminMenu = new JMenu();
        mnConfig = new JMenuItem();
        mnData = new JMenuItem();
        mnSerial = new JMenuItem();
        mnAddUser = new JMenuItem();
        mnRemoveUser = new JMenuItem();
        mnManControls = new JMenuItem();

        FormListener formListener = new FormListener();

        passwordDialog.setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        passwordDialog.setTitle("Enter Password");
        passwordDialog.setAlwaysOnTop(true);
        passwordDialog.setUndecorated(true);
        passwordDialog.setResizable(false);
        passwordDialog.setType(Type.POPUP);
        passwordDialog.addKeyListener(formListener);

        jPasswordField1.addActionListener(formListener);

        jLabel2.setFont(new Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Enter Password:");

        okPasswordBtn.setText("OK");
        okPasswordBtn.addActionListener(formListener);

        cancelPassBtn.setText("Cancel");
        cancelPassBtn.addActionListener(formListener);

        GroupLayout passwordDialogLayout = new GroupLayout(passwordDialog.getContentPane());
        passwordDialog.getContentPane().setLayout(passwordDialogLayout);
        passwordDialogLayout.setHorizontalGroup(passwordDialogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(passwordDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, 153, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okPasswordBtn)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelPassBtn)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        passwordDialogLayout.setVerticalGroup(passwordDialogLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(passwordDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(passwordDialogLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                    .addComponent(okPasswordBtn)
                    .addComponent(cancelPassBtn))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Tester Interface");

        jPanel1.setLayout(new AbsoluteLayout());

        pgmBtn.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        pgmBtn.setText("Program");
        pgmBtn.setPreferredSize(new Dimension(137, 100));
        pgmBtn.addActionListener(al);
        jPanel1.add(pgmBtn, new AbsoluteConstraints(0, 2, 173, 110));

        testBtn.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        testBtn.setText("Test");
        testBtn.setIconTextGap(2);
        testBtn.setPreferredSize(new Dimension(85, 100));
        testBtn.addActionListener(al);
        jPanel1.add(testBtn, new AbsoluteConstraints(179, 2, 165, 110));

        deviceLabel.setFont(new Font("Dubai Medium", 1, 24)); // NOI18N
        deviceLabel.setText("No Device Selected");
        deviceLabel.setAlignmentX(0.5F);
        deviceLabel.setFocusable(false);
        deviceLabel.setRequestFocusEnabled(false);
        jPanel1.add(deviceLabel, new AbsoluteConstraints(350, 40, 270, 32));

        textArea.setEditable(false);
        textArea.setBackground(new Color(51, 204, 255));
        textArea.setColumns(20);
        textArea.setFont(new Font("Segoe UI", 0, 28)); // NOI18N
        textArea.setLineWrap(true);
        textArea.setRows(5);
        textArea.setTabSize(4);
        textArea.setText("EAX2500 Tester Interface\n");
        textArea.setWrapStyleWord(true);
        textArea.setDisabledTextColor(new Color(204, 204, 204));
        textArea.setFocusable(false);
        textArea.setMargin(new Insets(5, 5, 5, 5));
        textArea.setRequestFocusEnabled(false);
        Preferences p = Preferences.userNodeForPackage(WindowFrame.class);
        int ci = p.getInt("BACKGROUND_COLOR", 0);
        //            p.putInt("BACKGROUND_COLOR", c.getRGB());
        //Preferences.userNodeForPackage(MainInterface.class).getInt("BACKGROUND_COLOR", ci);
        //if ( ci != -1 ){
            Color c = new Color(ci);
            textArea.setBackground(c);
            //}
        jScrollPane1.setViewportView(textArea);

        jPanel2.setLayout(new AbsoluteLayout());

        exitBtn.setFont(new Font("Tahoma", 1, 24)); // NOI18N
        exitBtn.setText("Exit");
        exitBtn.addActionListener(al);
        exitBtn.addActionListener(formListener);
        jPanel2.add(exitBtn, new AbsoluteConstraints(270, 0, 140, 110));

        jLabel3.setFont(new Font("Calibri", 1, 22)); // NOI18N
        jLabel3.setLabelFor(userBox);
        jLabel3.setText("Users:");
        jPanel2.add(jLabel3, new AbsoluteConstraints(70, 20, -1, 30));

        loginBtn.setFont(new Font("Tahoma", 1, 23)); // NOI18N
        loginBtn.setText("Login");
        loginBtn.setMargin(new Insets(4, 14, 4, 14));
        loginBtn.setPreferredSize(new Dimension(89, 42));
        loginBtn.addActionListener(al);
        jPanel2.add(loginBtn, new AbsoluteConstraints(80, 70, 171, -1));

        userBox.setFont(new Font("Tahoma", 1, 18)); // NOI18N
        userBox.setModel(new DefaultComboBoxModel<>(new String[] { "DMH", "SM", "TCM", "RJM", "SDO" }));
        userBox.addItemListener(formListener);
        userBox.addActionListener(formListener);
        jPanel2.add(userBox, new AbsoluteConstraints(130, 20, 107, -1));

        jMenuBar1.setPreferredSize(new Dimension(355, 40));

        jMenu1.setBorder(BorderFactory.createEtchedBorder());
        jMenu1.setText("File");
        jMenu1.setAlignmentX(1.0F);
        jMenu1.setAlignmentY(1.0F);
        jMenu1.setBorderPainted(false);
        jMenu1.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        jMenu1.setHorizontalAlignment(SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(SwingConstants.CENTER);
        jMenu1.setMargin(new Insets(0, 10, 0, 20));
        jMenu1.setMinimumSize(new Dimension(50, 0));
        jMenu1.setPreferredSize(new Dimension(70, 29));

        mnQuit.setFont(new Font("Segoe UI", 0, 22)); // NOI18N
        mnQuit.setText("Quit");
        mnQuit.setHorizontalAlignment(SwingConstants.TRAILING);
        mnQuit.setHorizontalTextPosition(SwingConstants.LEFT);
        mnQuit.setPreferredSize(new Dimension(70, 40));
        mnQuit.addActionListener(formListener);
        jMenu1.add(mnQuit);

        jMenuBar1.add(jMenu1);

        deviceMenu.setBorder(BorderFactory.createEtchedBorder());
        deviceMenu.setText("Device");
        deviceMenu.setAlignmentX(1.0F);
        deviceMenu.setAlignmentY(1.0F);
        deviceMenu.setBorderPainted(false);
        deviceMenu.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        deviceMenu.setMargin(new Insets(2, 5, 2, 5));
        deviceMenu.setPreferredSize(new Dimension(100, 29));
        jMenuBar1.add(deviceMenu);

        jMenu3.setBorder(BorderFactory.createEtchedBorder());
        jMenu3.setText("Config");
        jMenu3.setAlignmentX(1.0F);
        jMenu3.setAlignmentY(1.0F);
        jMenu3.setBorderPainted(false);
        jMenu3.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        jMenu3.setPreferredSize(new Dimension(90, 29));

        mnChangePass.setFont(new Font("Segoe UI", 0, 22)); // NOI18N
        mnChangePass.setText("Change Password");
        mnChangePass.setHorizontalAlignment(SwingConstants.LEFT);
        mnChangePass.setHorizontalTextPosition(SwingConstants.LEFT);
        mnChangePass.setPreferredSize(new Dimension(270, 32));
        jMenu3.add(mnChangePass);

        mnChangeColor.setFont(new Font("Segoe UI", 0, 22)); // NOI18N
        mnChangeColor.setText("Background Color");
        mnChangeColor.setHorizontalAlignment(SwingConstants.LEFT);
        mnChangeColor.setHorizontalTextPosition(SwingConstants.LEFT);
        mnChangeColor.setPreferredSize(new Dimension(270, 32));
        mnChangeColor.addActionListener(formListener);
        jMenu3.add(mnChangeColor);

        mnTimer.setFont(new Font("Segoe UI", 0, 22)); // NOI18N
        mnTimer.setText("Adjust Testing Delay Time");
        mnTimer.setHorizontalAlignment(SwingConstants.LEFT);
        mnTimer.setHorizontalTextPosition(SwingConstants.LEFT);
        mnTimer.setPreferredSize(new Dimension(270, 32));
        mnTimer.addActionListener(formListener);
        jMenu3.add(mnTimer);

        jMenuBar1.add(jMenu3);

        adminMenu.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        adminMenu.setText("Admin");
        adminMenu.setAlignmentX(1.0F);
        adminMenu.setAlignmentY(1.0F);
        adminMenu.setBorderPainted(false);
        adminMenu.setFont(new Font("Segoe UI", 0, 24)); // NOI18N
        adminMenu.setPreferredSize(new Dimension(100, 29));

        mnConfig.setFont(new Font("Segoe UI", 0, 22)); // NOI18N
        mnConfig.setText("Open Config");
        mnConfig.setHorizontalTextPosition(SwingConstants.LEFT);
        adminMenu.add(mnConfig);

        mnData.setFont(new Font("Segoe UI", 0, 22)); // NOI18N
        mnData.setText("Open Data Folder");
        mnData.setHorizontalTextPosition(SwingConstants.LEFT);
        adminMenu.add(mnData);

        mnSerial.setFont(new Font("Segoe UI", 0, 22)); // NOI18N
        mnSerial.setText("Set Serial Number");
        mnSerial.setHorizontalTextPosition(SwingConstants.LEFT);
        mnSerial.addActionListener(formListener);
        adminMenu.add(mnSerial);

        mnAddUser.setFont(new Font("Segoe UI", 0, 22)); // NOI18N
        mnAddUser.setText("Add User");
        mnAddUser.setHorizontalTextPosition(SwingConstants.LEFT);
        mnAddUser.addActionListener(formListener);
        adminMenu.add(mnAddUser);

        mnRemoveUser.setFont(new Font("Segoe UI", 0, 22)); // NOI18N
        mnRemoveUser.setText("Remove User");
        mnRemoveUser.setHorizontalTextPosition(SwingConstants.LEFT);
        mnRemoveUser.addActionListener(formListener);
        adminMenu.add(mnRemoveUser);

        mnManControls.setFont(new Font("Segoe UI", 0, 22)); // NOI18N
        mnManControls.setText("Manual Controls");
        mnManControls.setHorizontalTextPosition(SwingConstants.LEFT);
        adminMenu.add(mnManControls);

        jMenuBar1.add(adminMenu);

        setJMenuBar(jMenuBar1);

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 585, GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 414, GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, GroupLayout.PREFERRED_SIZE, 114, GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements ActionListener, ItemListener, KeyListener {
        FormListener() {}
        public void actionPerformed(ActionEvent evt) {
            if (evt.getSource() == exitBtn) {
                WindowFrame.this.exitBtnActionPerformed(evt);
            }
            else if (evt.getSource() == userBox) {
                WindowFrame.this.userBoxActionPerformed(evt);
            }
            else if (evt.getSource() == jPasswordField1) {
                WindowFrame.this.jPasswordField1ActionPerformed(evt);
            }
            else if (evt.getSource() == okPasswordBtn) {
                WindowFrame.this.okPasswordBtnActionPerformed(evt);
            }
            else if (evt.getSource() == cancelPassBtn) {
                WindowFrame.this.cancelPassBtnActionPerformed(evt);
            }
            else if (evt.getSource() == mnQuit) {
                WindowFrame.this.mnQuitActionPerformed(evt);
            }
            else if (evt.getSource() == mnChangeColor) {
                WindowFrame.this.mnChangeColorActionPerformed(evt);
            }
            else if (evt.getSource() == mnTimer) {
                WindowFrame.this.mnTimerActionPerformed(evt);
            }
            else if (evt.getSource() == mnSerial) {
                WindowFrame.this.mnSerialActionPerformed(evt);
            }
            else if (evt.getSource() == mnAddUser) {
                WindowFrame.this.mnAddUserActionPerformed(evt);
            }
            else if (evt.getSource() == mnRemoveUser) {
                WindowFrame.this.mnRemoveUserActionPerformed(evt);
            }
        }

        public void itemStateChanged(ItemEvent evt) {
            if (evt.getSource() == userBox) {
                WindowFrame.this.userBoxItemStateChanged(evt);
            }
        }

        public void keyPressed(KeyEvent evt) {
            if (evt.getSource() == passwordDialog) {
                WindowFrame.this.passwordDialogKeyPressed(evt);
            }
        }

        public void keyReleased(KeyEvent evt) {
        }

        public void keyTyped(KeyEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void mnQuitActionPerformed(ActionEvent evt) {//GEN-FIRST:event_mnQuitActionPerformed
        textArea.append(evt.paramString() + "\n");
        int v = JOptionPane.showConfirmDialog(rootPane, "Exit?", "Confirm", JOptionPane.YES_NO_OPTION);
        if (v == JOptionPane.YES_OPTION) {
            // TODO: Perform logout functions here
            System.exit(0);
        }
    }//GEN-LAST:event_mnQuitActionPerformed

    private void mnChangeColorActionPerformed(ActionEvent evt) {//GEN-FIRST:event_mnChangeColorActionPerformed
        // textArea.append(evt.paramString() + "\n");
        Color c = JColorChooser.showDialog(rootPane, "Select Background Color", textArea.getBackground());
        if (c != null) {
            textArea.setBackground(c);
            Preferences p = Preferences.userNodeForPackage(this.getClass());
            p.putInt("BACKGROUND_COLOR", c.getRGB());
            p.getInt("", WIDTH);
            try {
                p.flush();
            } catch (BackingStoreException ex) {
                Logger.getLogger(WindowFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_mnChangeColorActionPerformed

    private void mnTimerActionPerformed(ActionEvent evt) {//GEN-FIRST:event_mnTimerActionPerformed
        // TODO: Popup a dialog window with a slider to change the delay time.
        textArea.append(evt.paramString() + "\n");
    }//GEN-LAST:event_mnTimerActionPerformed

    private void mnAddUserActionPerformed(ActionEvent evt) {//GEN-FIRST:event_mnAddUserActionPerformed
        // TODO: Show add user dialog
    }//GEN-LAST:event_mnAddUserActionPerformed

    private void mnRemoveUserActionPerformed(ActionEvent evt) {//GEN-FIRST:event_mnRemoveUserActionPerformed
        // TODO show remove user dialog
    }//GEN-LAST:event_mnRemoveUserActionPerformed

    private void mnSerialActionPerformed(ActionEvent evt) {//GEN-FIRST:event_mnSerialActionPerformed
        // TODO show input dialog for the serial number
    }//GEN-LAST:event_mnSerialActionPerformed

    private void okPasswordBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_okPasswordBtnActionPerformed
        // TODO Check the password
    }//GEN-LAST:event_okPasswordBtnActionPerformed

    private void jPasswordField1ActionPerformed(ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void passwordDialogKeyPressed(KeyEvent evt) {//GEN-FIRST:event_passwordDialogKeyPressed
        System.out.println(evt.getKeyChar());
    }//GEN-LAST:event_passwordDialogKeyPressed

    private void cancelPassBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_cancelPassBtnActionPerformed
        passwordDialog.setVisible(false);
    }//GEN-LAST:event_cancelPassBtnActionPerformed

    private void exitBtnActionPerformed(ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        mnQuit.doClick();
    }//GEN-LAST:event_exitBtnActionPerformed

    private void userBoxItemStateChanged(ItemEvent evt) {//GEN-FIRST:event_userBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_userBoxItemStateChanged

    private void userBoxActionPerformed(ActionEvent evt) {//GEN-FIRST:event_userBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userBoxActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(WindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(WindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(WindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(WindowFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(() -> {
//            new WindowFrame().setVisible(true);
//        });
//    }
    private ActionListener al = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent e) {
            textArea.append(e.getActionCommand() + "\n");
        }
    };

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JMenu adminMenu;
    public JButton cancelPassBtn;
    public JLabel deviceLabel;
    private JMenu deviceMenu;
    public JButton exitBtn;
    public JLabel jLabel2;
    public JLabel jLabel3;
    private JMenu jMenu1;
    public JMenu jMenu3;
    public JMenuBar jMenuBar1;
    public JPanel jPanel1;
    public JPanel jPanel2;
    public JPasswordField jPasswordField1;
    public JScrollPane jScrollPane1;
    public JButton loginBtn;
    public JMenuItem mnAddUser;
    public JMenuItem mnChangeColor;
    public JMenuItem mnChangePass;
    public JMenuItem mnConfig;
    public JMenuItem mnData;
    public JMenuItem mnManControls;
    public JMenuItem mnQuit;
    public JMenuItem mnRemoveUser;
    public JMenuItem mnSerial;
    public JMenuItem mnTimer;
    public JButton okPasswordBtn;
    public JDialog passwordDialog;
    public JButton pgmBtn;
    public JButton testBtn;
    public JTextArea textArea;
    public JComboBox<String> userBox;
    // End of variables declaration//GEN-END:variables
}
